### PR TITLE
Fix/python version issue

### PR DESCRIPTION
**Pull request by mesaglio**
This pr solve #531 issue.

I change the `SetupContext` function to return an array of `*PythonContext` to force a test with `!` in version.

### CODE REVIEW

**Comment by mesaglio** [comment]
@imjasonh @kaniini

**Review by kaniini — APPROVED** [review]

**Comment by deitch** [comment]
@mesaglio I see melange tests failing on `python_test.go`, see for example this run https://github.com/chainguard-dev/melange/actions/runs/5517264026/jobs/10059642524?pr=542 . Is it related to this PR?

**Comment by mesaglio** [comment]
@deitch I think this test broken because in python convert test, this going to pypi to get the latest version and in the last version on `jsonschema` was added some deps like  `jsonschema-specifications>=2023.03.6` and we dont have this json file mocked.
I'm working on fix this.

**Comment by deitch** [comment]
Thanks @mesaglio ; kindly comment here when you have a fix.

**Comment by rawlingsj** [comment]
Wonder if we should revert the original PR and work on the fix adding the changes back in?  Currently CI is broken so it's blocking PRs merging and releasing.  

Unless the fix is pretty straightforward and can be added soon?

**Comment by mesaglio** [comment]
Hi @rawlingsj, yes you revert if you like. I'm woking on this right now.

**Pull request merged**
