### PR TITLE
Refactor the config/logging stuff out of build

### PR DESCRIPTION
**Pull request by Elizafox**
This is the preliminary part of work to refactor renovate to allow it to use var transforms and other future config infrastructure.

### CODE REVIEW

**Comment by kaniini** [comment]
Looks like some solid work!

Tests need to be fixed up, obviously, and once those are fixed, the linter should be happy too.  The integration tests appear OK.

**Comment by Elizafox** [comment]
> Looks like some solid work!
> 
> Tests need to be fixed up, obviously, and once those are fixed, the linter should be happy too. The integration tests appear OK.

On that. The big issue I'm having right now is trying to figure out how to sort the build test from the config test. They're sort of joined at the hip at the moment (to be fair, Build is a major consumer of the API). Most of the tests in pkg/build/build_test.go *look* like config tests at first glance, but also use `Build`. I'm not 100% sure how to solve this particular cross-cutting concern.

**Comment by Elizafox** [comment]
Sorry about the noise. I messed up my git history (forgot to sign commits and signoff a commit).

Git is not a very user-friendly tool when you have to amend history. :(

**Comment by Elizafox** [comment]
> > Looks like some solid work!
> > Tests need to be fixed up, obviously, and once those are fixed, the linter should be happy too. The integration tests appear OK.
> 
> On that. The big issue I'm having right now is trying to figure out how to sort the build test from the config test. They're sort of joined at the hip at the moment (to be fair, Build is a major consumer of the API). Most of the tests in pkg/build/build_test.go _look_ like config tests at first glance, but also use `Build`. I'm not 100% sure how to solve this particular cross-cutting concern.

I just decided to edit the existing tests and go with that for now. They also happen to test the config.

**Review by kaniini — APPROVED** [review]

**Pull request merged**
