### PR TITLE
Extract `melange sign` to a library

### PR DESCRIPTION
**Pull request by tcnghia**

### CODE REVIEW

**Review by k4leung4 — COMMENTED** [review]
should we add unit test?

**Comment by tcnghia** [comment]
> should we add unit test?

I don't have enough knowledge of how to do the key verification here to write a meaningful unit test for this. Do you have a suggestion on how I can do so?

**Comment by k4leung4** [comment]
> > should we add unit test?
> 
> I don't have enough knowledge of how to do the signature verification here to write a meaningful unit test for this. Do you have a suggestion on how I can do so?

i have even less of an idea then you
its definitely no worst than before, but having library code that arent tested doesnt seem right.

**Review by k4leung4 — DISMISSED** [review]

**Comment by tcnghia** [comment]
> > > should we add unit test?
> > 
> > 
> > I don't have enough knowledge of how to do the signature verification here to write a meaningful unit test for this. Do you have a suggestion on how I can do so?
> 
> i have even less of an idea then you its definitely no worst than before, but having library code that arent tested doesnt seem right.

@jonjohnsonjr  would RSAVerifySHA1Digest from go-apk work to verify package digest? I could try using that

**Review by k4leung4 — APPROVED** [review]

**Pull request merged**
