### PR TITLE
Only create build env SBOM if flag set

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
cc @puerco

**Comment by luhring** [comment]
related: #256

**Review by luhring — APPROVED** [review]

**Comment by kaniini** [comment]
I would rather not merge this.  The purpose of capturing the build environment in the SBOM is to allow the SBOM to be used as a source of truth when reproducing a build, and I have plans to make use of this functionality in Melange in the near future.  If the build environment is not captured by default, then we cannot move forward on verified reproducibility of Wolfi, unless an alternate design is implemented.

**Comment by jdolitsky** [comment]
closing in favor of #276

**Pull request closed without merging**
